quarkus:
#  log:
#    category:
#      "io.quarkus.grpc":
#        level: debug
#    level: debug
  shutdown:
    timeout: 5s
  generate-code:
    grpc:
      scan-for-proto: ru.expanse.quader:lib, ru.tinkoff.piapi:java-sdk-grpc-contract
  grpc:
    server:
      port: 9001
    clients:
      broker:
        plain-text: false
        tls:
          enabled: true
          trust-certificate-pem:
            certs: russian_trusted_root_ca.cer
        use-quarkus-grpc-client: true
        host: ${BROKER_GRPC_HOST}
        port: ${BROKER_GRPC_PORT}
    dev-mode:
      force-server-start: false
broker:
  api:
    token: ${BROKER_API_TOKEN}