"%prod":
  quarkus:
    application:
      name: bot
    log:
      console:
        json:
          enabled: false
      socket:
        enabled: true
        endpoint: fluent-bit:9880
        json:
          enabled: true
          log-format: ecs
    shutdown:
      timeout: 5s
    generate-code:
      grpc:
        scan-for-proto: ru.expanse.quader:lib, ru.tinkoff.piapi:java-sdk-grpc-contract
    grpc:
      server:
        use-separate-server: false
      clients:
        broker-client:
          plain-text: false
          tls:
            enabled: true
            trust-certificate-pem:
              certs: russian_trusted_root_ca.cer
          use-quarkus-grpc-client: true
          host: ${BROKER_GRPC_HOST}
          port: ${BROKER_GRPC_PORT}
  broker-client:
    api:
      token: ${BROKER_API_TOKEN}

"%dev":
  quarkus:
    log:
      console:
        json:
          enabled: false
      socket:
        enabled: false
    http:
      port: 8080
    shutdown:
      timeout: 5s
    generate-code:
      grpc:
        scan-for-proto: ru.expanse.quader:lib, ru.tinkoff.piapi:java-sdk-grpc-contract
    grpc:
      server:
        use-separate-server: false
      clients:
        broker-client:
          plain-text: false
          tls:
            enabled: true
            trust-certificate-pem:
              certs: russian_trusted_root_ca.cer
          use-quarkus-grpc-client: true
          host: ${BROKER_GRPC_HOST}
          port: ${BROKER_GRPC_PORT}
  broker-client:
    api:
      token: ${BROKER_API_TOKEN}
