quarkus:
  generate-code:
    grpc:
      scan-for-proto: ru.tinkoff.piapi:java-sdk-grpc-contract
  grpc:
    server:
      port: ${GRPC_PORT}
    clients:
      broker:
        host: ${BROKER_GRPC_HOST}
broker:
  api:
    token: ${BROKER_API_TOKEN}